services:
  sensor-map-app:
    build: .
    container_name: sensor-map-app-dev
    ports:
      - "8501:8501"
    volumes:
      # Mount data directory from host
      - ../../data:/app/data:ro
      # Mount app.py for development (enables hot reload without rebuild)
      - ./app.py:/app/app.py
      # Optional: Mount entire current directory for broader file watching
      # - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_BASE_URL_PATH=/sensor-map
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      # Enable file watching and auto-reload
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=poll
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
    restart: unless-stopped
    # Development: disable healthcheck for faster startup
    # healthcheck:
    #   test: [ "CMD", "curl", "-f", "http://localhost:8501/sensor-map/_stcore/health" ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    # Development: no resource limits for easier debugging
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1G
    #       cpus: '0.5'
    #     reservations:
    #       memory: 512M
    #       cpus: '0.25'
