version: '3.8'

services:
  sensor-map-app:
    build: .
    container_name: sensor-map-app
    ports:
      - "8501:8501"
    volumes:
      # Mount data directory from host
      - ../../data:/app/data:ro
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_BASE_URL_PATH=/sensor-map
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8501/sensor-map/_stcore/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Optional: resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
